name: Box16 Build CI
on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y make build-essential libgtk-3-dev libsdl2-dev
      - name: Build Box16 (Ubuntu)
        run: |
          cd build
          make
      - name: Archive Ubuntu build
        uses: actions/upload-artifact@v3
        with:
          name: box16-nr42.xx-linux
          path: build/box16/
  build-ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y make build-essential libgtk-3-dev libsdl2-dev
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "10.0"
      - name: Build Box16 (Ubuntu-Clang)
        run: |
          export CC=clang
          export CXX=clang++
          cd build
          make
  build-ubuntu-trace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y make build-essential libgtk-3-dev libsdl2-dev
      - name: Build Box16 (Ubuntu w/ Tracing)
        run: |
          cd build
          make trace
      - name: Archive Ubuntu build
        uses: actions/upload-artifact@v3
        with:
          name: box16-nr42.xx-linux-trace
          path: build/box16/
  build-ubuntu-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y make build-essential libgtk-3-dev libsdl2-dev
      - name: Build Box16 (Ubuntu)
        run: |
          cd build
          make debug
  build-win32-debug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x86
      - name: Build Box16 (Win32 Debug)
        run: |
          cd build\vs2022
          msbuild box16.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Debug -property:Platform=x86
  build-win32-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x86
      - name: Build Box16 (Win32 Release)
        run: |
          cd build\vs2022
          msbuild box16.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release -property:Platform=x86
          cd ..
          mkdir -p box16-Win32-Release
          cp vs2022/out/Win32/Release/Box16.exe box16-Win32-Release/
          cp vs2022/out/Win32/Release/box16-icon56-24.png box16-Win32-Release/
          cp vs2022/out/Win32/Release/icons.png box16-Win32-Release/
          cp vs2022/out/Win32/Release/README.box16 box16-Win32-Release/
          cp vs2022/out/Win32/Release/SDL2.dll box16-Win32-Release/
          cp vs2022/out/Win32/Release/zlibwapi.dll box16-Win32-Release/
      - name: Archive Win32-Release build
        uses: actions/upload-artifact@v3
        with:
          name: box16-nr42.xx-Win32
          path: build/box16-Win32-Release/
  build-win32-release-trace:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x86
      - name: Build Box16 (Win32 Release w/ Tracing)
        run: |
          cd build\vs2022
          msbuild box16.vcxproj -t:rebuild -verbosity:diag -property:Configuration="Release (Trace)" -property:Platform=x86
          cd ..
          mkdir -p box16-Win32-Release-Trace
          cp "vs2022/out/Win32/Release (TRACE)/Box16.exe" box16-Win32-Release-Trace/
          cp "vs2022/out/Win32/Release (TRACE)/box16-icon56-24.png" box16-Win32-Release-Trace/
          cp "vs2022/out/Win32/Release (TRACE)/icons.png" box16-Win32-Release-Trace/
          cp "vs2022/out/Win32/Release (TRACE)/README.box16" box16-Win32-Release-Trace/
          cp "vs2022/out/Win32/Release (TRACE)/SDL2.dll" box16-Win32-Release-Trace/
          cp "vs2022/out/Win32/Release (TRACE)/zlibwapi.dll" box16-Win32-Release-Trace/
      - name: Archive Win32-Release-Trace build
        uses: actions/upload-artifact@v3
        with:
          name: box16-nr42.xx-Win32-trace
          path: build/box16-Win32-Release-Trace/
  build-x64-debug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Build Box16 (x64 Debug)
        run: |
          cd build\vs2022
          msbuild box16.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Debug -property:Platform=x64
  build-x64-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Build Box16 (x64 Release)
        run: |
          cd build\vs2022
          msbuild box16.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release -property:Platform=x64
          cd ..
          mkdir -p box16-x64-Release
          cp vs2022/out/x64/Release/Box16.exe box16-x64-Release/
          cp vs2022/out/x64/Release/box16-icon56-24.png box16-x64-Release/
          cp vs2022/out/x64/Release/icons.png box16-x64-Release/
          cp vs2022/out/x64/Release/README.box16 box16-x64-Release/
          cp vs2022/out/x64/Release/SDL2.dll box16-x64-Release/
          cp vs2022/out/x64/Release/zlibwapi.dll box16-x64-Release/
      - name: Archive x64-Release build
        uses: actions/upload-artifact@v3
        with:
          name: box16-nr42.xx-x64
          path: build/box16-x64-Release/
  build-x64-release-trace:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Build Box16 (x64 Release w/ Tracing)
        run: |
          cd build\vs2022
          msbuild box16.vcxproj -t:rebuild -verbosity:diag -property:Configuration="Release (Trace)" -property:Platform=x64
          cd ..
          mkdir -p box16-x64-Release-Trace
          cp "vs2022/out/x64/Release (TRACE)/Box16.exe" box16-x64-Release-Trace/
          cp "vs2022/out/x64/Release (TRACE)/box16-icon56-24.png" box16-x64-Release-Trace/
          cp "vs2022/out/x64/Release (TRACE)/icons.png" box16-x64-Release-Trace/
          cp "vs2022/out/x64/Release (TRACE)/README.box16" box16-x64-Release-Trace/
          cp "vs2022/out/x64/Release (TRACE)/SDL2.dll" box16-x64-Release-Trace/
          cp "vs2022/out/x64/Release (TRACE)/zlibwapi.dll" box16-x64-Release-Trace/
      - name: Archive x64-Release-Trace build
        uses: actions/upload-artifact@v3
        with:
          name: box16-nr42.xx-x64-trace
          path: build/box16-x64-Release-Trace/

